main: and7697_main.cpp and7697_Media.h and7697_Media.cpp and7697_Book.h and7697_Book.cpp and7697_Movie.h and7697_Movie.cpp and7697_Video_Game.h and7697_Video_Game.cpp and7697_Music_Album.h and7697_Music_Album.cpp and7697_Television_Show_Season.h and7697_Television_Show_Season.cpp and7697_Bundle.h and7697_Bundle.cpp and7697_Librarian.h and7697_Librarian.cpp and7697_Customer.h and7697_Customer.cpp
	g++ -std=c++11 -o and7697_main and7697_main.cpp and7697_Media.h and7697_Media.cpp and7697_Book.h and7697_Book.cpp and7697_Movie.h and7697_Movie.cpp and7697_Video_Game.h and7697_Video_Game.cpp and7697_Music_Album.h and7697_Music_Album.cpp and7697_Television_Show_Season.h and7697_Television_Show_Season.cpp and7697_Bundle.h and7697_Bundle.cpp and7697_Librarian.h and7697_Librarian.cpp and7697_Customer.h and7697_Customer.cpp
	./and7697_main
clean:
	-rm -f *.o and7697_main
