main1: and7697_Mobile_Arm.h and7697_Mobile_Arm.cpp and7697_Super_Arm.h and7697_Super_Arm.cpp and7697_Extendable_Arm.h and7697_Extendable_Arm.cpp and7697_Powered_Arm.h and7697_Powered_Arm.cpp and7697_Arm_Robot.h and7697_Arm_Robot.cpp and7697_Mobile_Robot.h and7697_Mobile_Robot.cpp and7697_Robot.h and7697_Robot.cpp
	g++ -std=c++11 -o and7697_main1 and7697_main1.cpp and7697_Mobile_Arm.h and7697_Mobile_Arm.cpp and7697_Super_Arm.h and7697_Super_Arm.cpp and7697_Extendable_Arm.h and7697_Extendable_Arm.cpp and7697_Powered_Arm.h and7697_Powered_Arm.cpp and7697_Arm_Robot.h and7697_Arm_Robot.cpp and7697_Mobile_Robot.h and7697_Mobile_Robot.cpp and7697_Robot.h and7697_Robot.cpp
	./and7697_main1
main2: and7697_Mobile_Arm.h and7697_Mobile_Arm.cpp and7697_Super_Arm.h and7697_Super_Arm.cpp and7697_Extendable_Arm.h and7697_Extendable_Arm.cpp and7697_Powered_Arm.h and7697_Powered_Arm.cpp and7697_Arm_Robot.h and7697_Arm_Robot.cpp and7697_Mobile_Robot.h and7697_Mobile_Robot.cpp and7697_Robot.h and7697_Robot.cpp
	g++ -std=c++11 -o and7697_main2 and7697_main2.cpp and7697_Mobile_Arm.h and7697_Mobile_Arm.cpp and7697_Super_Arm.h and7697_Super_Arm.cpp and7697_Extendable_Arm.h and7697_Extendable_Arm.cpp and7697_Powered_Arm.h and7697_Powered_Arm.cpp and7697_Arm_Robot.h and7697_Arm_Robot.cpp and7697_Mobile_Robot.h and7697_Mobile_Robot.cpp and7697_Robot.h and7697_Robot.cpp
	./and7697_main2
clean:
	-rm -f *.o and7697_main1 and7697_main2
