main: and7697_Date.h and7697_Date.cpp and7697_Transaction.h and7697_Transaction.cpp and7697_Transaction_List.h and7697_Transaction_List.cpp and7697_main.cpp
	g++ -std=c++11 -o and7697_main and7697_main.cpp
	./and7697_main
clean:
	-rm -f *.o and7697_main
