main: txz5041_main.cpp txz5041_month.cpp
	g++ --std=c++11 -o txz5041_main txz5041_main.cpp
	./txz5041_main
test: txz5041_month_test.cpp txz5041_month.cpp
	g++ --std=c++11 -o txz5041_month_test txz5041_month_test.cpp
	./txz5041_month_test
clean:
	-rm -f *.o txz5041_main txz5041_month_test

