main: and7697_Extendable_Arm.h and7697_Extendable_Arm.cpp and7697_Powered_Arm.h and7697_Powered_Arm.cpp and7697_Arm_Robot.h and7697_Arm_Robot.cpp and7697_Mobile_Robot.h and7697_Mobile_Robot.cpp and7697_Robot.h and7697_Robot.cpp
	g++ -std=c++11 -o and7697_main and7697_main.cpp and7697_Extendable_Arm.h and7697_Extendable_Arm.cpp and7697_Powered_Arm.h and7697_Powered_Arm.cpp and7697_Arm_Robot.h and7697_Arm_Robot.cpp and7697_Mobile_Robot.h and7697_Mobile_Robot.cpp and7697_Robot.h and7697_Robot.cpp
	./and7697_main
clean:
	-rm -f *.o and7697_main
