main: Employee.h Employee.cpp Manager.h Manager.cpp Sales.h Sales.cpp SalesManager.h SalesManager.cpp Stock_boy.h Stock_boy.cpp Clerk.h Clerk.cpp main.cpp
	g++ -std=c++11 -o main main.cpp Employee.h Employee.cpp Manager.h Manager.cpp Sales.h Sales.cpp SalesManager.h SalesManager.cpp Stock_boy.h Stock_boy.cpp Clerk.h Clerk.cpp
	./main
clean:
	-rm -f *.o main
