#!/bin/bash

make clean
make test_age
./test_age
make test_genre
./test_genre
make test_video_store
./test_video_store
make test_media_type
./test_media_type
make test_patron
./test_patron
make test_media
./test_media

# make test_view -- Must test the GUI interactively

