CXXFLAGS = -std=c++11

full_credit: Secret_Code_1.cpp
	$(CXX) $(CXXFLAGS) -o Secret_Code_1 Secret_Code_1.cpp

extra_credit: Secret_Code_2.cpp
	$(CXX) $(CXXFLAGS) -o Secret_Code_2 Secret_Code_2.cpp

clean:
	rm Secret_Code_1 Secret_Code_2
